package Quiz;

/**
* Quiz/QuestionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from quiz.idl
* Friday, September 20, 2013 11:55:54 AM CEST
*/


/* Data structure defining a question composed of id, sentence and alternatives */
public final class QuestionHolder implements org.omg.CORBA.portable.Streamable
{
  public Quiz.Question value = null;

  public QuestionHolder ()
  {
  }

  public QuestionHolder (Quiz.Question initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Quiz.QuestionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Quiz.QuestionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Quiz.QuestionHelper.type ();
  }

}
