package Quiz;


/**
* Quiz/Question.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from quiz.idl
* Friday, September 20, 2013 11:55:54 AM CEST
*/


/* Data structure defining a question composed of id, sentence and alternatives */
public abstract class Question implements org.omg.CORBA.portable.StreamableValue
{
  public int id = (int)0;
  public String sentence = null;
  public Quiz.Alternative alternatives[] = null;

  private static String[] _truncatable_ids = {
    Quiz.QuestionHelper.id ()
  };

  public String[] _truncatable_ids() {
    return _truncatable_ids;
  }

  public void _read (org.omg.CORBA.portable.InputStream istream)
  {
    this.id = istream.read_long ();
    this.sentence = istream.read_string ();
    this.alternatives = Quiz.QuestionPackage.AlternativeSeqHelper.read (istream);
  }

  public void _write (org.omg.CORBA.portable.OutputStream ostream)
  {
    ostream.write_long (this.id);
    ostream.write_string (this.sentence);
    Quiz.QuestionPackage.AlternativeSeqHelper.write (ostream, this.alternatives);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Quiz.QuestionHelper.type ();
  }
} // class Question
