package Quiz;


/**
* Quiz/QuizServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from quiz.idl
* Friday, September 20, 2013 11:55:54 AM CEST
*/


/* Interface for the Quiz Game server object. This interface provides the methods that
	   can be used by clients to play the game.*/
public interface QuizServer extends QuizServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface QuizServer
