package Quiz;


/**
* Quiz/Alternative.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from quiz.idl
* Friday, September 20, 2013 11:55:54 AM CEST
*/


/* Data structure defining one alternative for a Question */
public abstract class Alternative implements org.omg.CORBA.portable.StreamableValue
{
  public char id = (char)0;
  public String sentence = null;

  private static String[] _truncatable_ids = {
    Quiz.AlternativeHelper.id ()
  };

  public String[] _truncatable_ids() {
    return _truncatable_ids;
  }

  public void _read (org.omg.CORBA.portable.InputStream istream)
  {
    this.id = istream.read_char ();
    this.sentence = istream.read_string ();
  }

  public void _write (org.omg.CORBA.portable.OutputStream ostream)
  {
    ostream.write_char (this.id);
    ostream.write_string (this.sentence);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Quiz.AlternativeHelper.type ();
  }
} // class Alternative
