package Quiz;

/**
* Quiz/AlternativeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from quiz.idl
* Friday, September 20, 2013 11:55:54 AM CEST
*/


/* Data structure defining one alternative for a Question */
public final class AlternativeHolder implements org.omg.CORBA.portable.Streamable
{
  public Quiz.Alternative value = null;

  public AlternativeHolder ()
  {
  }

  public AlternativeHolder (Quiz.Alternative initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Quiz.AlternativeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Quiz.AlternativeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Quiz.AlternativeHelper.type ();
  }

}
