package Quiz;


/**
* Quiz/CompleteQuestion.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from quiz.idl
* Friday, September 20, 2013 11:55:54 AM CEST
*/


/* Data structure defining a complete question, which extends the Question structure
	   adding the correct alternatives for the question. */
public abstract class CompleteQuestion extends Quiz.Question
{
  public char correctAlternatives[] = null;

  private static String[] _truncatable_ids = {
    Quiz.CompleteQuestionHelper.id ()
  };

  public String[] _truncatable_ids() {
    return _truncatable_ids;
  }

  public void _read (org.omg.CORBA.portable.InputStream istream)
  {
    super._read (istream);
    this.correctAlternatives = Quiz.CompleteQuestionPackage.CharSeqHelper.read (istream);
  }

  public void _write (org.omg.CORBA.portable.OutputStream ostream)
  {
    super._write (ostream);
    Quiz.CompleteQuestionPackage.CharSeqHelper.write (ostream, this.correctAlternatives);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Quiz.CompleteQuestionHelper.type ();
  }
} // class CompleteQuestion
