package Quiz;


/**
* Quiz/QuizServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from quiz.idl
* Friday, September 20, 2013 11:55:54 AM CEST
*/


/* Interface for the Quiz Game server object. This interface provides the methods that
	   can be used by clients to play the game.*/
public interface QuizServerOperations 
{

  /* Method for the creation of a new question on the server object. The question
  		   object should be created on the client and sent to the server using this method.
  		   On the server, the question is persisted on the memory or disk, so it can be
  		   returned to the clients on future call. The submitted question should be complete,
  		   containing the correct answers. It returns the question id of the created question.
  		   This method should allow the client to select the question id, in case the id is
  		   already taken it should automatically assign an id to the question. Note that a
  		   question may have more than one correct alternatives. */
  int newQuestion (Quiz.CompleteQuestion question) throws Quiz.QuizServerPackage.QuizException;

  /* Returns a question to the client selected randomly form the set of questions stored at
  		   the server. A Question object that does not contains the correct answers is returned. */
  boolean getRandomQuestion (Quiz.QuestionHolder randomQuestion) throws Quiz.QuizServerPackage.QuizException;

  /* The client can submit answers to one of the questions that he knows the id. The server
  		   will check the answer and return true if it is correct of false if not. The out correct
  		   parameter should be filled with the write answer. */
  boolean answerQuestion (int questionId, char[] answer, Quiz.QuizServerPackage.alternativesIdsHolder correct) throws Quiz.QuizServerPackage.QuizException;

  /* Removes a question that has the specified id from the server. */
  int removeQuestion (int questionId) throws Quiz.QuizServerPackage.QuizException;
} // interface QuizServerOperations
