package Quiz;


/**
* Quiz/QuizServerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from quiz.idl
* Friday, September 20, 2013 11:55:54 AM CEST
*/


/* Interface for the Quiz Game server object. This interface provides the methods that
	   can be used by clients to play the game.*/
abstract public class QuizServerHelper
{
  private static String  _id = "IDL:Quiz/QuizServer:1.0";

  public static void insert (org.omg.CORBA.Any a, Quiz.QuizServer that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Quiz.QuizServer extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Quiz.QuizServerHelper.id (), "QuizServer");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Quiz.QuizServer read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_QuizServerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Quiz.QuizServer value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Quiz.QuizServer narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Quiz.QuizServer)
      return (Quiz.QuizServer)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Quiz._QuizServerStub stub = new Quiz._QuizServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Quiz.QuizServer unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Quiz.QuizServer)
      return (Quiz.QuizServer)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Quiz._QuizServerStub stub = new Quiz._QuizServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
