package Quiz.QuizServerPackage;


/**
* Quiz/QuizServerPackage/alternativesIdsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from quiz.idl
* Friday, September 20, 2013 11:55:54 AM CEST
*/


/* auxiliary definition of sequence type for alternatives */
public final class alternativesIdsHolder implements org.omg.CORBA.portable.Streamable
{
  public char value[] = null;

  public alternativesIdsHolder ()
  {
  }

  public alternativesIdsHolder (char[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Quiz.QuizServerPackage.alternativesIdsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Quiz.QuizServerPackage.alternativesIdsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Quiz.QuizServerPackage.alternativesIdsHelper.type ();
  }

}
