package Quiz.QuizServerPackage;

/**
* Quiz/QuizServerPackage/QuizExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from quiz.idl
* Friday, September 20, 2013 11:55:54 AM CEST
*/

public final class QuizExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public Quiz.QuizServerPackage.QuizException value = null;

  public QuizExceptionHolder ()
  {
  }

  public QuizExceptionHolder (Quiz.QuizServerPackage.QuizException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Quiz.QuizServerPackage.QuizExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Quiz.QuizServerPackage.QuizExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Quiz.QuizServerPackage.QuizExceptionHelper.type ();
  }

}
