package Quiz.QuizServerPackage;


/**
* Quiz/QuizServerPackage/QuizException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from quiz.idl
* Friday, September 20, 2013 11:55:54 AM CEST
*/

public final class QuizException extends org.omg.CORBA.UserException
{
  public String reason = null;

  public QuizException ()
  {
    super(QuizExceptionHelper.id());
  } // ctor

  public QuizException (String _reason)
  {
    super(QuizExceptionHelper.id());
    reason = _reason;
  } // ctor


  public QuizException (String $reason, String _reason)
  {
    super(QuizExceptionHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class QuizException
