package Quiz.QuestionPackage;


/**
* Quiz/QuestionPackage/AlternativeSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from quiz.idl
* Friday, September 20, 2013 11:55:54 AM CEST
*/

public final class AlternativeSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public Quiz.Alternative value[] = null;

  public AlternativeSeqHolder ()
  {
  }

  public AlternativeSeqHolder (Quiz.Alternative[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Quiz.QuestionPackage.AlternativeSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Quiz.QuestionPackage.AlternativeSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Quiz.QuestionPackage.AlternativeSeqHelper.type ();
  }

}
