package Quiz.QuestionPackage;


/**
* Quiz/QuestionPackage/AlternativeSeqHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from quiz.idl
* Friday, September 20, 2013 11:55:54 AM CEST
*/

abstract public class AlternativeSeqHelper
{
  private static String  _id = "IDL:Quiz/Question/AlternativeSeq:1.0";

  public static void insert (org.omg.CORBA.Any a, Quiz.Alternative[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Quiz.Alternative[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = Quiz.AlternativeHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (Quiz.QuestionPackage.AlternativeSeqHelper.id (), "AlternativeSeq", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Quiz.Alternative[] read (org.omg.CORBA.portable.InputStream istream)
  {
    Quiz.Alternative value[] = null;
    int _len0 = istream.read_long ();
    value = new Quiz.Alternative[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = Quiz.AlternativeHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Quiz.Alternative[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      Quiz.AlternativeHelper.write (ostream, value[_i0]);
  }

}
